In [1]:
import numpy as np

In [2]:
a = np.array([1,4,6])
b = np.array([4,6,1])

In [3]:
# addition
print(a+b)

[ 5 10  7]


In [5]:
# substraction
print(a-b)
print(b-a)

[-3 -2  5]
[ 3  2 -5]


In [9]:
# division 
print(a/b)
print(a//b) # -> integers value
print(b//a) # -> integers value

[0.25       0.66666667 6.        ]
[0 0 6]
[4 1 0]


In [7]:
# multipliacation
print(a*b)

[ 4 24  6]


In [10]:
# modulus
print(a%b)

[1 4 0]


In [11]:
# exponent
print(a**b) # -> power
print(a**2)

[   1 4096    6]
[ 1 16 36]


### Universe functions -> Ufuncs

In [12]:
arr = np.array([1,4,9,16])

In [14]:
# sqrt (square root)
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [17]:
# exponentioal -> np.exp -> e^x , where x is any integer
print(np.exp([2,3]))

[ 7.3890561  20.08553692]


In [18]:
# sine function -> np.sin
angles = np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]
