In [1]:
import numpy as np

In [2]:
a = np.array([2,4])
b = np.array([3,6])

combine = np.concatenate((a,b))

In [4]:
print(combine)

[2 4 3 6]


In [8]:
# Vstack -> verticle stack
a = np.array([[2,4],[1,2]])
b = np.array([[3,6],[2,8]])
stack = np.vstack((a,b))
print(stack)

[[2 4]
 [1 2]
 [3 6]
 [2 8]]


In [7]:
# Hstack -> Horizontal stack
a = np.array([[2,4],[1,2]])
b = np.array([[3,6],[2,8]])
stack = np.hstack((a,b))
print(stack)

[[2 4 3 6]
 [1 2 2 8]]


In [10]:
# Stack -> ((a,b), axis = )
# axis 0 = row wise
# axis 1 = column wise
a = np.array([[2,4],[1,2]])
b = np.array([[3,6],[2,8]])
stack = np.stack((a,b),axis = 0)
print(stack)

[[[2 4]
  [1 2]]

 [[3 6]
  [2 8]]]


In [11]:
a = np.array([[2,4],[1,2]])
b = np.array([[3,6],[2,8]])
stack = np.stack((a,b),axis = 1)
print(stack)

[[[2 4]
  [3 6]]

 [[1 2]
  [2 8]]]
