In [2]:
import numpy as np
import time

In [ ]:
range = np.arange(0,11,1) #star #stop(not included) #step (like how many numbers to jump)
range

array([ 0,  2,  4,  6,  8, 10])

In [19]:
space = np.linspace(0,1,5) #start #stop #number b/w them
space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
array = np.logspace(1,3,3) #logarithmtic scale array -> 10^1 10^2 10^3..... 3 points
array
#np.logspace = (starting , ending -> powers , here 3 -> number of values )

array([  10.,  100., 1000.])

In [31]:
# np.zeros -> this will create arrays full of zeros
array = np.zeros([2,5]) # 2 rows and 5 columns 
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
array = np.ones([2,4]) #array full of one
array
# default it gives float value but we can change it's datatype too
arr = np.ones([2,3], dtype = int)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
# np.full create an array full of any value
array = np.full([2,5], 4) #row , column , and default value
array

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [60]:
# np.empty -> uninitialized array -> create an array without setting any value
"""
🚀 Why does np.empty() exist then?

Because it is:

Faster than zeros() or ones()

Useful when you are going to overwrite all values immediately
"""
array1 = np.empty([2,3])
array1

array([[5.e-324, 5.e-324, 5.e-324],
       [5.e-324, 5.e-324, 5.e-324]])

In [63]:
array = np.random.rand(10) # random float b/w 0-1
array1 = np.random.rand(2,4)
array
array1

array([[0.60178145, 0.19941387, 0.93781302, 0.57167517],
       [0.7088034 , 0.37612439, 0.33641465, 0.79728962]])

In [64]:
# np.random.randn -> random floats from standard normal distribution
# meaning mean(avg) is going to be 0 and standart deviation going to be 1 
array = np.random.randn(3,5)
array 


array([[-0.19090676,  1.1518478 ,  0.33578204,  0.21895885,  0.75469555],
       [ 0.08784252, -1.31676332,  0.31383223, -0.3591382 , -0.98368014],
       [-1.30077126, -1.05299074, -0.81997884,  0.87270152, -0.30763031]])

In [67]:
# np.random.randint -> random intigers
array = np.random.randint(2,100) 
array

7

In [70]:
array = np.random.randint(2,100, size=(2,3)) #start , stop , dimensions / number of values
array

array([[99, 12, 94],
       [66, 91, 53]])