In [39]:
import numpy as np
import time

In [2]:
a = [2,3,4,5,6]

In [3]:
a[0]

2

In [6]:
a[0:3:1] #starting index , ending index (never included) , step value

[2, 3, 4]

In [7]:
array = np.array([1,2,3,4,5,6,7,8,9])

In [9]:
array[0:5:2]
print(array[::3])

[1 4 7]


## negative indexing

In [18]:
array = np.array([1,2,3,4,5,6,7,8,9])
print(array[-1:-6:-1])

[9 8 7 6 5]


In [15]:
print(array[3])

4


## multidimensional slicing 

In [20]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [24]:
print(matrix[0:2, 0:3])
# or 
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [32]:
print(matrix[ 1: , 0:2])

[[4 5]
 [7 8]]


In [43]:
# np.take -> built in function for indexing and slicing
start = time.time()
array = np.array([10,20,30,40,50,60])
index = [0,5]
print(np.take(array,index))
end = time.time()
print("Time taken:", end - start)

[10 60]
Time taken: 0.0013840198516845703


In [52]:
start = time.time()
array = [10,20,30,40,50,60]

print(array[0])
print(array[5])
end = time.time()
print(end - start)

10
60
0.0003528594970703125


In [53]:
arr_np = np.array([10,20,30,40,50,60])
arr_list = [10,20,30,40,50,60]

start = time.time()
print(arr_np[0], arr_np[5])
print("NumPy indexing:", time.time() - start)

start = time.time()
print(arr_list[0], arr_list[5])
print("List indexing:", time.time() - start)

10 60
NumPy indexing: 0.00020003318786621094
10 60
List indexing: 7.82012939453125e-05
