In [1]:
import numpy as np

# whenever we create a view our original arrays going to effected but
# whenever we create a copy our original arrays will not be effected and it will be uncahnged and our copy will be effected

In [5]:
# view 
array = np.array([1,2,3,4,5,6,7])
view = array[1:5]
view

array([2, 3, 4, 5])

In [7]:
view[0] = 69
view

array([69,  3,  4,  5])

In [8]:
array

array([ 1, 69,  3,  4,  5,  6,  7])

In [9]:
# so original array is also changed here 

In [12]:
# copy
copy = array[1:3].copy()
copy

array([69,  3])

In [13]:
copy[0] = 59
copy

array([59,  3])

In [14]:
array

array([ 1, 69,  3,  4,  5,  6,  7])

In [15]:
copy = array.copy()
copy

array([ 1, 69,  3,  4,  5,  6,  7])

In [16]:
copy[3] = 79
copy

array([ 1, 69,  3, 79,  5,  6,  7])

In [17]:
array

array([ 1, 69,  3,  4,  5,  6,  7])

In [ ]:
# so here original array is not effected at all